import { MenuItem } from "../graphql/generated-types"

const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Cappuccino",
    description: "Hey, it's coffee",
    price: 4.5,
    glutenFree: true,
    vegetarian: true,
    ingredients: ["coffee", "milk"],
  },
  {
    id: "2",
    name: "Latte",
    description: "Hey, it's coffee",
    price: 4.5,
    glutenFree: true,
    vegetarian: true,
    ingredients: ["coffee", "milk"],
  },
  {
    id: "3",
    name: "Long Black",
    description: "Hey, it's just coffee",
    price: 4,
    glutenFree: true,
    vegetarian: true,
    ingredients: ["coffee"],
  },
  {
    id: "4",
    name: "Short Black",
    description: "Hey, it's just a small coffee",
    price: 4,
    glutenFree: true,
    vegetarian: true,
    ingredients: ["coffee"],
  },
  {
    id: "5",
    name: "Blueberry Muffin",
    description: "Muffins are just ugly cupcakes",
    price: 4,
    glutenFree: false,
    vegetarian: true,
    ingredients: ["flour", "blueberries"],
  },
  {
    id: "6",
    name: "Oat Muffin",
    description: "Muffins are just ugly cupcakes",
    price: 4,
    glutenFree: false,
    vegetarian: true,
    ingredients: ["flour", "oats"],
  },
  {
    id: "7",
    name: "Croissant",
    description: "Puff pastry and butter",
    price: 3,
    glutenFree: false,
    vegetarian: true,
    ingredients: ["flour", "butter"],
  },
  {
    id: "8",
    name: "Ham and Cheese Croissant",
    description: "Puff pastry and butter, stuffed with ham and cheese",
    price: 5,
    glutenFree: false,
    vegetarian: false,
    ingredients: ["flour", "butter", "ham", "cheese"],
  },
  {
    id: "9",
    name: "Croissant with marmalade",
    description: "Puff pastry and butter, with a sweet spread",
    price: 4,
    glutenFree: false,
    vegetarian: true,
    ingredients: ["flour", "butter", "marmalade"],
  },
  {
    id: "10",
    name: "Gluten free toast with marmalade",
    description: "If only it was real bread",
    price: 5,
    glutenFree: true,
    vegetarian: true,
    ingredients: ["gluten free bread", "marmalade"],
  },
]

export { menuItems }
